<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>omh</string>
		<string>omnis</string>
	</array>
	<key>name</key>
	<string>Omnis</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#repository</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#methods</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Variables like $PARAM1, $TM_SELECTION</string>
			<key>match</key>
			<string>\$([A-Za-z][A-Za-z0-9_]+)</string>
			<key>name</key>
			<string>meta.method-call.omh</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^[\s]*\;</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.omh</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.block.omh</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\;\;</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.omh</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.omh</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\#(NULL|SHIFT)|(\bk[A-Z]{1}[A-Za-z0-9_]+)</string>
					<key>name</key>
					<string>constant.language.omh</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^[\s]*(Do code method|Do method|Do)\s</string>
					<key>name</key>
					<string>keyword.control.omh</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\sReturns\s|\sReturns\n</string>
					<key>name</key>
					<string>keyword.control.omh</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^[\s]*(as|If|Begin statement|Begin text block|Break to end of Loop|Break to end of loop|Calculate|Case|Default|Else If|Else|End For|End If|end statement|End Switch|End text block|End While|For|from|Get statement|Get text block|JavaScript|Platform newline|Repeat|Send to trace log|Sta|step|Switch|Text|to|Until|While|Working message|Begin SQL script|Get SQL script|End SQL script|Execute SQL script|list lines|SQL|Fetch next row into|Build list|Sta|Quit method|End statement)\b|\bstep|\b(as)\b|from|On\s.*?\s</string>
					<key>name</key>
					<string>keyword.control.omh</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.omh</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.omh</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.omh</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_escaped_char</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string_placeholder</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.omh</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.omh</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.omh</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_escaped_char</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string_placeholder</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\#[A-Z0-9]+|\$c.*?\.</string>
					<key>name</key>
					<string>variable.language.omh</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.omh</string>
	<key>uuid</key>
	<string>c9bbc41d-d7e5-4afc-98ac-95b2b7e354bd</string>
</dict>
</plist>
